name: SimpleWarp
main: SimpleWarp\SimpleWarp
version: "1.0"
author: Falk
api: "1.0.0"

commands:
 warp:
  permission: simplewarp.warp
  description: Warp to a location
  usage: /warp <NAME>
 addwarp:
  permission: simplewarp.manage
  description: Add a new warp point
  usage: /addwarp <NAME>
 delwarp:
  permission: simplewarp.manage
  description: Delete a warp point
  usage: /delwarp <NAME>

permissions:
 simplewarp:
  default: op
  description: Top level SimpleWarp permission
  children:
   simplewarp.warp.*:
    default: op
    description: Allows warp to a set warp location.
   simplewarp.manage:
    default: op
    description: Manage all warps
   simplewarp.all:
    default: op
    description: Allows warp to all warp locations
