#    >=>>=>   >=>                         >=>           >=>        >=>
#  >=>    >=> >=>                         >=>           >=>        >=>
#   >=>       >=> >===>>=>>==>  >=> >=>   >=>   >==>    >=>   >>   >=>    >=> >=>  >> >==> >=> >=>
#     >=>     >=>  >=>  >>  >=> >>   >=>  >=> >>   >=>  >=>  >=>   >=>  >=>   >=>   >=>    >>   >=>
#        >=>  >=>  >=>  >>  >=> >>   >=>  >=> >>===>>=> >=> >> >=> >=> >=>    >=>   >=>    >>   >=>
#  >=>    >=> >=>  >=>  >>  >=> >=> >=>   >=> >>        >> >>    >===>  >=>   >=>   >=>    >=> >=>
#    >=>>=>   >=> >==>  >>  >=> >=>      >==>  >====>   >=>        >=>   >==>>>==> >==>    >=>
#                               >=>      The original warp plugin for PocketMine           >=>

display-exact-coordinates: false